// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPqkLW6--ux-dOq61y_vIQr8ugnzye3ho',
    appId: '1:391481229981:web:bdf2df585995360ff48a74',
    messagingSenderId: '391481229981',
    projectId: 'comp4768-final-project',
    authDomain: 'comp4768-final-project.firebaseapp.com',
    storageBucket: 'comp4768-final-project.appspot.com',
    measurementId: 'G-TZF9RH26NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfddPhMfVaHcBFUhGmw3DmBWadKuWuPM0',
    appId: '1:391481229981:android:1de47a4f6f87d2daf48a74',
    messagingSenderId: '391481229981',
    projectId: 'comp4768-final-project',
    storageBucket: 'comp4768-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASUbe4UJLPYsH6YqJYrrLuvFVWGrIoIHY',
    appId: '1:391481229981:ios:1f97a502633de1faf48a74',
    messagingSenderId: '391481229981',
    projectId: 'comp4768-final-project',
    storageBucket: 'comp4768-final-project.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASUbe4UJLPYsH6YqJYrrLuvFVWGrIoIHY',
    appId: '1:391481229981:ios:2da17b00df642ad3f48a74',
    messagingSenderId: '391481229981',
    projectId: 'comp4768-final-project',
    storageBucket: 'comp4768-final-project.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
